### ISSUE TITLE
Vscode debug on win7: time out waiting for debugger connection

### ISSUE THREAD

**Issue by hwasinR** [Microsoft/vscode-docs#2171]
**I use anaconda to install python lib and my setting json is:**
`{
    "python.pythonPath": "D:\\Anaconda\\python.exe",
    "python.terminal.activateEnvironment": false,
}`
**below is my traceback:**
`(base) C:\Users\Administrator\hello>cd c:\Users\Administrator\hello && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && D:\Anaconda\python.exe c:\Users\Administrator\.vscode\extensions\ms-python.python-2018.9.2\pythonFiles\experimental\ptvsd_launcher.py 1606 c:\Users\Administrator\hello\.vscode\launch.json "
Could not connect to localhost: 1606
Traceback (most recent call last):
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2018.9.2\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 1751, in main
    debugger.connect(host, port)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2018.9.2\pythonFiles\experimental\ptvsd\ptvsd\_vendored\pydevd\pydevd.py", line 355, in connect
    s = start_client(host, port)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2018.9.2\pythonFiles\experimental\ptvsd\ptvsd\pydevd_hooks.py", line 85, in <lambda>
    _start_client = (lambda h, p: start_client(daemon, h, p))
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2018.9.2\pythonFiles\experimental\ptvsd\ptvsd\pydevd_hooks.py", line 65, in start_client
    sock, start_session = daemon.start_client((host, port))
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2018.9.2\pythonFiles\experimental\ptvsd\ptvsd\daemon.py", line 207, in start_client
    connect(client, addr)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2018.9.2\pythonFiles\experimental\ptvsd\ptvsd\socket.py", line 178, in connect
    sock.connect(addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。`
**The chinese means "the target computer rejects the connection", sry for my poor English.**

**Comment by gregvanl** [comment]
Moving to the ms-python.python extension repository as not a documentation issue.

**Comment by gregvanl** [comment]
This issue was moved to Microsoft/vscode-python#3253
