### ISSUE TITLE
Extension tests not found on Azure Pipeline

### ISSUE THREAD

**Issue by chrisjsewell** [Microsoft/vscode-docs#2314]
I have an extension, initially created using the standard `yo code` template, and successfully uploaded to the market place. I have created a test suite, which works correctly when running locally (i.e. pressing F5), and I now wanted to add CI testing to the [Github repo](https://github.com/chrisjsewell/vscode-moose).

I followed the instructions on [Continuous Integration](https://code.visualstudio.com/api/working-with-extensions/continuous-integration) and created a [config YAML file](https://github.com/chrisjsewell/vscode-moose/blob/master/azure-pipelines.yml). The extension compiles successfully in Azure, however it appears that no tests are discovered.  

For example, in [this build](https://dev.azure.com/chrisjsewell/vscode/_build/results?buildId=4) I intentionally introduced a failing test, but it still passes.

Is there a step I'm missing, or a good way to debug the problem?

PS: I posted [this question on Stackoverflow](https://stackoverflow.com/questions/53957757/vs-code-extension-tests-not-found-on-azure-pipeline) a week ago, but received no replies. Hence, escalating it to an issue.

**Comment by bpasero** [comment]
@willsmythe fyi

**Comment by gregvanl** [comment]
Hi @chrisjsewell, sounds like you are unblocked but I'm not sure this is a documentation issue. Is the request that the yo code generated tests be modified to output missing dependency errors?

**Comment by brandonkoch6** [comment]
I have encountered this as well.  The azure-pipelines.yml that is given in the example of the CI doesn't actually pick up the tests and run them as part of the pipeline.  The test script works locally but when run on Azure DevOps, it never runs the tests.  I'm not sure I understand how @chrisjsewell worked around it, but the documentation definitely needs to change.

**Comment by chrisjsewell** [comment]
@gregvanl So I would suggest that the core VS Code test executable should not return a passing (i.e. 0) exit code, if the tests fail to run. 

For example, in [this build](https://dev.azure.com/chrisjsewell/vscode/_build/results?buildId=23), the `macOS Job` runs the tests as: 

    /Users/vsts/agent/2.144.0/work/1/s/.vscode-test/stable/Visual Studio Code.app/Contents/MacOS/Electron /Users/vsts/agent/2.144.0/work/1/s/out/test --extensionDevelopmentPath=/Users/vsts/agent/2.144.0/work/1/s --extensionTestsPath=/Users/vsts/agent/2.144.0/work/1/s/out/test

Whose exit status is 0, which is a false positive. Whereas, the `Mocha_macOS` job runs exactly the same tests as:

    node ./node_modules/mocha/bin/_mocha -u tdd --timeout 999999 --colors out/test/**/*.js

Whose exit status is 1, and clearly indicates in the error trace `Error: Cannot find module 'chai'`.

I imagine the VS Code executable is throwing the same error but, for whatever reason, is catching it and returning normally.

**Comment by willsmythe** [comment]
@gregvanl - let me know if you need any support from the Azure Pipelines team on this. It does sound like either the behavior of the test runner needs to change (e.g. return the appropriate non-zero exit code so the pipeline fails), or the sample Pipelines YAML file needs to be updated to run the tests differently.

**Comment by joaomoreno** [comment]
@bpasero Please check @chrisjsewell's comments on our test runner script: https://github.com/Microsoft/vscode-docs/issues/2314#issuecomment-451628542

**Comment by bpasero** [comment]
We do propagate the exit code of the mocha test to electrons exit function, but maybe that got broken with some Electron update.

**Comment by bpasero** [comment]
Here: https://github.com/Microsoft/vscode/blob/f599942a5f1ce23445eb1dd7e0ff799ab7a0a175/src/vs/workbench/api/node/extHostExtensionService.ts#L599

**Comment by chrisjsewell** [comment]
Hey @joaomoreno a) I directly copy/pasted the script from [Continuous Intergration](https://code.visualstudio.com/api/working-with-extensions/continuous-integration) and b) I think your missing the point of what I said; it's not that tests won't fail, it's that the entire test suite will not run if there is an import failure during the tests.

For example, in your (failing) test file (`<name>.test.ts`), add `import * as chai from 'chai';`, but don't include the `chai` package in your `package.json`. In my tests, this caused the tests to not run, but the jobs to return a 0 exit status

**Comment by joaomoreno** [comment]
> it's not that tests won't fail, it's that the entire test suite will not run if there is an import failure during the tests

Makes sense. Leaving it to @bpasero for investigation.

**Comment by bpasero** [comment]
This is NOT a problem with the exit code as you can easily see in this case where I run "`npm run test`" on an extension where I caused a test failure:

![image](https://user-images.githubusercontent.com/900690/50839356-65f73a00-1360-11e9-808c-037ba8e42004.png)

**Comment by chrisjsewell** [comment]
Hey @bpasero please read my comments above. This is only an issue with tests failing because of import errors (i.e. missing dependencies in the `package.json`), not general assertion failures. 

With vs code executable:

```
2019-01-02T22:53:58.9820940Z ##[section]Starting: Run tests
2019-01-02T22:53:58.9824920Z ==============================================================================
2019-01-02T22:53:58.9825050Z Task         : Command Line
2019-01-02T22:53:58.9825150Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2019-01-02T22:53:58.9825250Z Version      : 2.142.2
2019-01-02T22:53:58.9825340Z Author       : Microsoft Corporation
2019-01-02T22:53:58.9825450Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2019-01-02T22:53:58.9825550Z ==============================================================================
2019-01-02T22:53:59.1500940Z Generating script.
2019-01-02T22:53:59.1524290Z Script contents:
2019-01-02T22:53:59.1524670Z node node_modules/vscode/bin/test
2019-01-02T22:53:59.1593870Z [command]/bin/bash --noprofile --norc /Users/vsts/agent/2.144.0/work/_temp/f4ec721f-dd80-4f32-94dc-ffa305812af4.sh
2019-01-02T22:53:59.5549570Z ### VS Code Extension Test Run ###
2019-01-02T22:53:59.5555100Z Current working directory: /Users/vsts/agent/2.144.0/work/1/s
2019-01-02T22:54:00.1685450Z Downloading VS Code into "/Users/vsts/agent/2.144.0/work/1/s/.vscode-test/stable" from: https://vscode-update.azurewebsites.net/1.30.1/darwin/stable
2019-01-02T22:54:06.3880390Z Running extension tests: /Users/vsts/agent/2.144.0/work/1/s/.vscode-test/stable/Visual Studio Code.app/Contents/MacOS/Electron /Users/vsts/agent/2.144.0/work/1/s/out/test --extensionDevelopmentPath=/Users/vsts/agent/2.144.0/work/1/s --extensionTestsPath=/Users/vsts/agent/2.144.0/work/1/s/out/test
2019-01-02T22:54:07.4800850Z ‌[main 10:54:07 PM]‌ update#setState idle‌
2019-01-02T22:54:07.4801140Z 
2019-01-02T22:54:09.3676580Z nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
2019-01-02T22:54:09.3677450Z 
2019-01-02T22:54:09.3678870Z Run `npm config delete prefix` or `nvm use --delete-prefix v6.14.4 --silent` to unset it.
2019-01-02T22:54:09.3679010Z 
2019-01-02T22:54:16.0690420Z Tests exited with code: 0
2019-01-02T22:54:16.0965330Z ##[section]Finishing: Run tests
```

and directly with Mocha:

```
2019-01-02T22:53:58.5165870Z ##[section]Starting: Run Tests
2019-01-02T22:53:58.5170120Z ==============================================================================
2019-01-02T22:53:58.5170240Z Task         : npm
2019-01-02T22:53:58.5170350Z Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Package Management.
2019-01-02T22:53:58.5170470Z Version      : 1.144.0
2019-01-02T22:53:58.5170550Z Author       : Microsoft Corporation
2019-01-02T22:53:58.5170650Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
2019-01-02T22:53:58.5170760Z ==============================================================================
2019-01-02T22:53:58.8207780Z SYSTEMVSSCONNECTION exists true
2019-01-02T22:53:59.2087500Z SYSTEMVSSCONNECTION exists true
2019-01-02T22:54:00.8154530Z [command]/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm --version
2019-01-02T22:54:01.0337180Z 6.4.1
2019-01-02T22:54:01.5371400Z [command]/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm config list
2019-01-02T22:54:01.7824010Z npm info it worked if it ends with ok
2019-01-02T22:54:01.7825160Z npm verb cli [ '/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/node',
2019-01-02T22:54:01.7825800Z npm verb cli   '/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm',
2019-01-02T22:54:01.7825940Z ; cli configs
2019-01-02T22:54:01.7826510Z npm verb cli   'config',
2019-01-02T22:54:01.7827040Z npm verb cli   'list' ]
2019-01-02T22:54:01.7827160Z npm info using npm@6.4.1
2019-01-02T22:54:01.7827240Z npm info using node@v8.15.0
2019-01-02T22:54:01.7827330Z npm verb exit [ 0, true ]
2019-01-02T22:54:01.7827420Z npm timing npm Completed in 41ms
2019-01-02T22:54:01.7827500Z npm info ok 
2019-01-02T22:54:01.7828030Z metrics-registry = "https://registry.npmjs.org/"
2019-01-02T22:54:01.7828160Z scope = ""
2019-01-02T22:54:01.7828710Z user-agent = "npm/6.4.1 node/v8.15.0 darwin x64"
2019-01-02T22:54:01.7828810Z 
2019-01-02T22:54:01.7828890Z ; environment configs
2019-01-02T22:54:01.7828990Z loglevel = "verbose"
2019-01-02T22:54:01.7829090Z userconfig = "/Users/vsts/agent/2.144.0/work/1/npm/23.npmrc"
2019-01-02T22:54:01.7829150Z 
2019-01-02T22:54:01.7829240Z ; node bin location = /Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/node
2019-01-02T22:54:01.7829350Z ; cwd = /Users/vsts/agent/2.144.0/work/1/s
2019-01-02T22:54:01.7829430Z ; HOME = /Users/vsts
2019-01-02T22:54:01.7829960Z ; "npm config ls -l" to show all defaults.
2019-01-02T22:54:01.7830030Z 
2019-01-02T22:54:01.7833570Z [command]/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm run mocha
2019-01-02T22:54:02.2666310Z 
2019-01-02T22:54:02.2667910Z npm info it worked if it ends with ok
2019-01-02T22:54:02.2668910Z npm verb cli [ '/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/node',
2019-01-02T22:54:02.2669550Z npm verb cli   '/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm',
2019-01-02T22:54:02.2670140Z npm verb cli   'run',
2019-01-02T22:54:02.2670660Z npm verb cli   'mocha' ]
2019-01-02T22:54:02.2670790Z npm info using npm@6.4.1
2019-01-02T22:54:02.2670900Z npm info using node@v8.15.0
2019-01-02T22:54:02.2671460Z npm verb run-script [ 'premocha', 'mocha', 'postmocha' ]
2019-01-02T22:54:02.2671580Z npm info lifecycle moose@0.7.0~premocha: moose@0.7.0
2019-01-02T22:54:02.2671690Z npm info lifecycle moose@0.7.0~mocha: moose@0.7.0
2019-01-02T22:54:02.2671790Z module.js:550
2019-01-02T22:54:02.2671870Z     throw err;
2019-01-02T22:54:02.2671950Z     ^
2019-01-02T22:54:02.2672000Z 
2019-01-02T22:54:02.2672520Z Error: Cannot find module 'chai'
2019-01-02T22:54:02.2672660Z     at Function.Module._resolveFilename (module.js:548:15)
2019-01-02T22:54:02.2672760Z     at Function.Module._load (module.js:475:25)
2019-01-02T22:54:02.2672860Z     at Module.require (module.js:597:17)
2019-01-02T22:54:02.2672950Z     at require (internal/module.js:11:18)
2019-01-02T22:54:02.2675990Z     at Object.<anonymous> (/Users/vsts/agent/2.144.0/work/1/s/out/test/moose_doc.test.js:9:14)
2019-01-02T22:54:02.2676130Z     at Module._compile (module.js:653:30)
2019-01-02T22:54:02.2676450Z     at Object.Module._extensions..js (module.js:664:10)
2019-01-02T22:54:02.2676550Z     at Module.load (module.js:566:32)
2019-01-02T22:54:02.2676640Z     at tryModuleLoad (module.js:506:12)
2019-01-02T22:54:02.2676730Z     at Function.Module._load (module.js:498:3)
2019-01-02T22:54:02.2676830Z     at Module.require (module.js:597:17)
2019-01-02T22:54:02.2676920Z     at require (internal/module.js:11:18)
2019-01-02T22:54:02.2677030Z     at /Users/vsts/agent/2.144.0/work/1/s/node_modules/mocha/lib/mocha.js:231:27
2019-01-02T22:54:02.2677130Z     at Array.forEach (<anonymous>)
2019-01-02T22:54:02.2677240Z     at Mocha.loadFiles (/Users/vsts/agent/2.144.0/work/1/s/node_modules/mocha/lib/mocha.js:228:14)
2019-01-02T22:54:02.2677370Z     at Mocha.run (/Users/vsts/agent/2.144.0/work/1/s/node_modules/mocha/lib/mocha.js:536:10)
2019-01-02T22:54:02.2677510Z     at Object.<anonymous> (/Users/vsts/agent/2.144.0/work/1/s/node_modules/mocha/bin/_mocha:573:18)
2019-01-02T22:54:02.2677620Z     at Module._compile (module.js:653:30)
2019-01-02T22:54:02.2677720Z     at Object.Module._extensions..js (module.js:664:10)
2019-01-02T22:54:02.2677820Z     at Module.load (module.js:566:32)
2019-01-02T22:54:02.2677920Z     at tryModuleLoad (module.js:506:12)
2019-01-02T22:54:02.2678010Z     at Function.Module._load (module.js:498:3)
2019-01-02T22:54:02.2678110Z     at Function.Module.runMain (module.js:694:10)
2019-01-02T22:54:02.2678200Z     at startup (bootstrap_node.js:204:16)
2019-01-02T22:54:02.2678290Z     at bootstrap_node.js:625:3
2019-01-02T22:54:02.2678910Z npm verb lifecycle moose@0.7.0~mocha: unsafe-perm in lifecycle true
2019-01-02T22:54:02.2680170Z npm verb lifecycle moose@0.7.0~mocha: PATH: /Users/vsts/hostedtoolcache/node/8.15.0/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/vsts/agent/2.144.0/work/1/s/node_modules/.bin:/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin:/usr/local/lib/ruby/gems/2.5.0/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy
2019-01-02T22:54:02.2680570Z npm verb lifecycle moose@0.7.0~mocha: CWD: /Users/vsts/agent/2.144.0/work/1/s
2019-01-02T22:54:02.2680690Z npm info lifecycle moose@0.7.0~mocha: Failed to exec mocha script
2019-01-02T22:54:02.2681820Z npm verb stack Error: moose@0.7.0 mocha: `node ./node_modules/mocha/bin/_mocha -u tdd --timeout 999999 --colors out/test/**/*.js`
2019-01-02T22:54:02.2682010Z npm verb stack Exit status 1
2019-01-02T22:54:02.2682770Z npm verb stack     at EventEmitter.<anonymous> (/Users/vsts/hostedtoolcache/node/8.15.0/x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
2019-01-02T22:54:02.2682960Z npm verb stack     at emitTwo (events.js:126:13)
2019-01-02T22:54:02.2683060Z npm verb stack     at EventEmitter.emit (events.js:214:7)
2019-01-02T22:54:02.2683750Z npm verb stack     at ChildProcess.<anonymous> (/Users/vsts/hostedtoolcache/node/8.15.0/x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2019-01-02T22:54:02.2683930Z npm verb stack     at emitTwo (events.js:126:13)
2019-01-02T22:54:02.2684030Z npm verb stack     at ChildProcess.emit (events.js:214:7)
2019-01-02T22:54:02.2684140Z npm verb stack     at maybeClose (internal/child_process.js:915:16)
2019-01-02T22:54:02.2684260Z npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-01-02T22:54:02.2684370Z npm verb pkgid moose@0.7.0
2019-01-02T22:54:02.2684450Z npm verb cwd /Users/vsts/agent/2.144.0/work/1/s
2019-01-02T22:54:02.2684550Z npm verb Darwin 17.7.0
2019-01-02T22:54:02.2684670Z npm verb argv "/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/node" "/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm" "run" "mocha"
2019-01-02T22:54:02.2685250Z npm verb node v8.15.0
2019-01-02T22:54:02.2685550Z npm verb npm  v6.4.1
2019-01-02T22:54:02.2685650Z npm ERR! code ELIFECYCLE
2019-01-02T22:54:02.2685730Z npm ERR! errno 1
2019-01-02T22:54:02.2686490Z npm ERR! moose@0.7.0 mocha: `node ./node_modules/mocha/bin/_mocha -u tdd --timeout 999999 --colors out/test/**/*.js`
2019-01-02T22:54:02.2686650Z npm ERR! Exit status 1
2019-01-02T22:54:02.2686770Z npm ERR! 
2019-01-02T22:54:02.2686860Z npm ERR! Failed at the moose@0.7.0 mocha script.
2019-01-02T22:54:02.2686960Z > moose@0.7.0 mocha /Users/vsts/agent/2.144.0/work/1/s
2019-01-02T22:54:02.2687580Z > node ./node_modules/mocha/bin/_mocha -u tdd --timeout 999999 --colors out/test/**/*.js
2019-01-02T22:54:02.2687680Z 
2019-01-02T22:54:02.2687840Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-01-02T22:54:02.2687960Z npm verb exit [ 1, true ]
2019-01-02T22:54:02.2688050Z npm timing npm Completed in 277ms
2019-01-02T22:54:02.2688120Z 
2019-01-02T22:54:02.2688210Z npm ERR! A complete log of this run can be found in:
2019-01-02T22:54:02.2688820Z npm ERR!     /Users/vsts/.npm/_logs/2019-01-02T22_54_02_252Z-debug.log
2019-01-02T22:54:02.3275300Z Found npm debug log, make sure the path matches with the one in npm's output: /Users/vsts/.npm/_logs/2019-01-02T22_54_02_252Z-debug.log
2019-01-02T22:54:02.3275510Z 0 info it worked if it ends with ok
2019-01-02T22:54:02.3276060Z 1 verbose cli [ '/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/node',
2019-01-02T22:54:02.3276620Z 1 verbose cli   '/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm',
2019-01-02T22:54:02.3277140Z 1 verbose cli   'run',
2019-01-02T22:54:02.3277640Z 1 verbose cli   'mocha' ]
2019-01-02T22:54:02.3277760Z 2 info using npm@6.4.1
2019-01-02T22:54:02.3277840Z 3 info using node@v8.15.0
2019-01-02T22:54:02.3278360Z 4 verbose run-script [ 'premocha', 'mocha', 'postmocha' ]
2019-01-02T22:54:02.3278520Z 5 info lifecycle moose@0.7.0~premocha: moose@0.7.0
2019-01-02T22:54:02.3278610Z 6 info lifecycle moose@0.7.0~mocha: moose@0.7.0
2019-01-02T22:54:02.3279150Z 7 verbose lifecycle moose@0.7.0~mocha: unsafe-perm in lifecycle true
2019-01-02T22:54:02.3280420Z 8 verbose lifecycle moose@0.7.0~mocha: PATH: /Users/vsts/hostedtoolcache/node/8.15.0/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/vsts/agent/2.144.0/work/1/s/node_modules/.bin:/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin:/usr/local/lib/ruby/gems/2.5.0/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy
2019-01-02T22:54:02.3280790Z 9 verbose lifecycle moose@0.7.0~mocha: CWD: /Users/vsts/agent/2.144.0/work/1/s
2019-01-02T22:54:02.3281350Z 10 silly lifecycle moose@0.7.0~mocha: Args: [ '-c',
2019-01-02T22:54:02.3281950Z 10 silly lifecycle   'node ./node_modules/mocha/bin/_mocha -u tdd --timeout 999999 --colors out/test/**/*.js' ]
2019-01-02T22:54:02.3282120Z 11 silly lifecycle moose@0.7.0~mocha: Returned: code: 1  signal: null
2019-01-02T22:54:02.3282240Z 12 info lifecycle moose@0.7.0~mocha: Failed to exec mocha script
2019-01-02T22:54:02.3282870Z 13 verbose stack Error: moose@0.7.0 mocha: `node ./node_modules/mocha/bin/_mocha -u tdd --timeout 999999 --colors out/test/**/*.js`
2019-01-02T22:54:02.3283000Z 13 verbose stack Exit status 1
2019-01-02T22:54:02.3283650Z 13 verbose stack     at EventEmitter.<anonymous> (/Users/vsts/hostedtoolcache/node/8.15.0/x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
2019-01-02T22:54:02.3283810Z 13 verbose stack     at emitTwo (events.js:126:13)
2019-01-02T22:54:02.3283920Z 13 verbose stack     at EventEmitter.emit (events.js:214:7)
2019-01-02T22:54:02.3284560Z 13 verbose stack     at ChildProcess.<anonymous> (/Users/vsts/hostedtoolcache/node/8.15.0/x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2019-01-02T22:54:02.3285210Z 13 verbose stack     at emitTwo (events.js:126:13)
2019-01-02T22:54:02.3285320Z 13 verbose stack     at ChildProcess.emit (events.js:214:7)
2019-01-02T22:54:02.3285430Z 13 verbose stack     at maybeClose (internal/child_process.js:915:16)
2019-01-02T22:54:02.3285550Z 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-01-02T22:54:02.3285660Z 14 verbose pkgid moose@0.7.0
2019-01-02T22:54:02.3285760Z 15 verbose cwd /Users/vsts/agent/2.144.0/work/1/s
2019-01-02T22:54:02.3285840Z 16 verbose Darwin 17.7.0
2019-01-02T22:54:02.3285970Z 17 verbose argv "/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/node" "/Users/vsts/hostedtoolcache/node/8.15.0/x64/bin/npm" "run" "mocha"
2019-01-02T22:54:02.3286090Z 18 verbose node v8.15.0
2019-01-02T22:54:02.3286170Z 19 verbose npm  v6.4.1
2019-01-02T22:54:02.3286270Z 20 error code ELIFECYCLE
2019-01-02T22:54:02.3286360Z 21 error errno 1
2019-01-02T22:54:02.3286980Z 22 error moose@0.7.0 mocha: `node ./node_modules/mocha/bin/_mocha -u tdd --timeout 999999 --colors out/test/**/*.js`
2019-01-02T22:54:02.3287140Z 22 error Exit status 1
2019-01-02T22:54:02.3287230Z 23 error Failed at the moose@0.7.0 mocha script.
2019-01-02T22:54:02.3287340Z 23 error This is probably not a problem with npm. There is likely additional logging output above.
2019-01-02T22:54:02.3287450Z 24 verbose exit [ 1, true ]
2019-01-02T22:54:02.3287510Z 
2019-01-02T22:54:02.3349440Z ##[error]Error: Npm failed with return code: 1
2019-01-02T22:54:02.3377710Z ##[section]Finishing: Run Tests
```
