### ISSUE TITLE
Unable to start Python kernel - VS Code with pipenv + pyenv on WSL2

### ISSUE THREAD

**Issue by brybalicious** [microsoft/vscode-docs#3975]
Running smoothly on a virtual environment until 24 hours ago when I experienced an abrupt power failure. Since then, no new virtual environments are able to access the Python kernel on VS Code. Running Jupyter notebooks works fine from e.g. the command line.

Pipenv supposedly automatically sets up a pyenv virtual environment when a python version is set in a project's Pipfile. However, looking at the following output, it is unclear that that is happening.

I suspect that how Pipenv and Pyenv interact - where python is available from within a virtual environment - may have something to do with the failure.

I typically receive one of two errors: 
"Unable to start session for kernel Python 3. Select another kernel to launch with." 
OR
"heartbeat..."

######################################
Dump of Python console output from vscode:
######################################

User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.7 ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-09-01 23:51:44: Detection of Python Interpreter for Command python3.7 and args  failed as file  does not exist
> python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> pipenv --version
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/production-l1NzpQPe/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/.local/share/virtualenvs/production-l1NzpQPe/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/.local/share/virtualenvs/production-l1NzpQPe/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> pipenv --venv
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> pipenv --py
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
Error 2020-09-01 23:51:46: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu/home/spacefarer/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/spacefarer/.config/Code/User/settings.json')
	at _handleError (/home/spacefarer/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/out/vs/server/remoteExtensionHostProcess.js:696:249)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async v.readText (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:1:495638)
	at async p.doesFileNeedToBeFixed (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:953520)
	at async /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:952647
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:952593)
	at async p.updateTestSettings (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2020-09-01 23:51:46: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu/mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev/.vscode/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev/.vscode/settings.json')
	at _handleError (/home/spacefarer/.vscode-server/bin/a0479759d6e9ea56afa657e454193f72aef85bd0/out/vs/server/remoteExtensionHostProcess.js:696:249)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async v.readText (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:1:495638)
	at async p.doesFileNeedToBeFixed (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:953520)
	at async /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:952647
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:952593)
	at async p.updateTestSettings (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:48:952220)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Starting Jedi Python language engine.
Python interpreter path: /usr/bin/python3
Error 2020-09-01 23:51:46: Failed to get interpreter information for '/home/spacefarer/.pyenv/shims/python3.7' [Error: Command failed: "/home/spacefarer/.pyenv/shims/python3.7" "/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py" "/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/interpreterInfo.py"
pyenv: python3.7: command not found

The `python3.7' command exists in these Python versions:
  3.7.9

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

	at ChildProcess.exithandler (child_process.js:290:12)
	at ChildProcess.emit (events.js:200:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: '"/home/spacefarer/.pyenv/shims/python3.7" ' +
    '"/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py" ' +
    '"/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/interpreterInfo.py"'
}
> ~/.local/share/virtualenvs/production-l1NzpQPe/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.local/share/virtualenvs/production-l1NzpQPe/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.local/share/virtualenvs/production-l1NzpQPe/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> conda --version
> pipenv --version
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> pipenv --venv
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> pipenv --py
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py pip --version
Starting Jedi Python language engine.
Python interpreter path: ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/c/Users/spacefarer/Gradyent/Ypenburg/dev
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/completion.py
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/completion.py
Error 2020-09-01 23:52:33: stderr jediProxy Error (stderr) /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/completion.py:598: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  sys_path=sys.path,
/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/completion.py:598: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  sys_path=sys.path,
/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/completion.py:598: DeprecationWarning: Use the code keyword argument instead.
  sys_path=sys.path,
/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/completion.py:598: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  sys_path=sys.path,

Error 2020-09-01 23:52:33: stderr jediProxy Error (stderr) /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2020-09-01 23:52:41: Kernel died [r [Error]: [IPKernelApp] ERROR | Invalid Message

	at t._next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:780911)
	at t.__tryOrUnsub (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:5463)
	at t.next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:4632)
	at t._next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:3736)
	at t.next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:3407)
	at t.next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:8976)
	at /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:9:49971
	at /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:76768
	at /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:76986
	at Immediate._onImmediate (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:78555)
	at processImmediate (internal/timers.js:439:21)] 
Error 2020-09-01 23:53:40: Raw session failed to start in given timeout
Error 2020-09-01 23:53:40: Failed to connect raw kernel session: Error: Unable to start session for kernel Python 3. Select another kernel to launch with.
Error 2020-09-01 23:53:40: DataScience Error [g [Error]: Unable to start session for kernel Python 3. Select another kernel to launch with.
	at m.connect (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:562194)]
> ~/.local/share/virtualenvs/dev-ELUkbB6e/bin/python ~/.vscode-server/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2020-09-02 00:00:02: Kernel died [r [Error]: [IPKernelApp] ERROR | Invalid Message

	at t._next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:780911)
	at t.__tryOrUnsub (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:5463)
	at t.next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:4632)
	at t._next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:3736)
	at t.next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:3407)
	at t.next (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:24:8976)
	at /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:9:49971
	at /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:76768
	at /home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:76986
	at Immediate._onImmediate (/home/spacefarer/.vscode-server/extensions/ms-python.python-2020.8.105369/out/client/extension.js:46:78555)
	at processImmediate (internal/timers.js:439:21)]

**Comment by brybalicious** [comment]
Is this the root of the problem?

(FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu/home/user/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/user/.config/Code/User/settings.json')

I have no directory '/Code' lower than '/.config'

**Comment by JoshuaPartlow** [comment]
Hi @brybalicious - This goes beyond a doc issue, so I'm going to move this to the Python extension repo. Hopefully they'll be better able to help you there.
