### ISSUE TITLE
Django Tut python manage.py runserver not working...

### ISSUE THREAD

**Issue by eformx** [microsoft/vscode-docs#4457]
I installed django (newbie) and I see the manage.py file but when I try to run the server as per the Django tut it raises all the following errors in my virtual env.  How do I run this?

```
PS C:\Users\eform\hello_django> & c:/Users/eform/hello_django/.venv_django/Scripts/Activate.ps1
(.venv_django) PS C:\Users\eform\hello_django> python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\eform\miniconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\eform\miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\apps\config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\eform\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\contrib\auth\models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\contrib\auth\base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\db\models\base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\db\models\base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\db\models\options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\utils\connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\utils\connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\db\utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\db\utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "C:\Users\eform\miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\eform\hello_django\.venv_django\lib\site-packages\django\db\backends\sqlite3\base.py", line 15, in <module>
    from sqlite3 import dbapi2 as Database
  File "C:\Users\eform\miniconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\eform\miniconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
```

**Comment by JoshuaPartlow** [comment]
Hi @eformx - Could you provide a little more information about your environment? What OS are you running on? What installation(s) of Python are you using (Anaconda, miniconda, Python.org, etc) and how did you get it (installer, built from source, etc)? I see the lines where you activate the environment, but could you confirm how you went about creating it?

**Comment by eformx** [comment]
Trying to navigate to the Django tutorial at https://code.visualstudio.com/docs/python/tutorial-django which does not work. 
I am training for a  job, so don't have time to wait for a fix to VSCode or the tutorial, unfortunately this is typical Microsoft training material...they need to run tests on all tutorials when either the development tool changes.  Same problem with VS 2019, in theory a great free tool, but docs are very poor.   Switched to PyCharm Pro which works perfectly.

**Comment by JoshuaPartlow** [comment]
Hi @eformx - I'm sorry to hear the tutorial isn't working for you. I have run through the initial steps to see if I could duplicate your issue, but wasn't able to. The tutorial steps are working ok for me. It sounds like you've moved on, so I'll close the issue, but if you still want to try to get things working with VS Code, please feel free to re-open.
