### ISSUE TITLE
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/microsoft/vscode-docs?pullRequest=4721) <br/>All CLA requirements met.

### ISSUE THREAD

**Issue by Dwalinnewyork** [microsoft/vscode-docs#4725]
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/signed)](https://cla.opensource.microsoft.com/microsoft/vscode-docs?pullRequest=4721) <br/>All CLA requirements met.

_Originally posted by @microsoft-cla[bot] in https://github.com/microsoft/vscode-docs/issues/4721#issuecomment-892308738_

**Comment by Dwalinnewyork** [comment]
5/8/2564 1:01:28 - Microsoft VSIX Installer
5/8/2564 1:01:28 - -------------------------------------------
5/8/2564 1:01:28 - vsixinstaller.exe version:
5/8/2564 1:01:28 - 16.11.9
5/8/2564 1:01:28 - -------------------------------------------
5/8/2564 1:01:28 - Command line parameters:
5/8/2564 1:01:28 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Apidwalin\Desktop\msbuild\InstallerProjects.vsix
5/8/2564 1:01:28 - -------------------------------------------
5/8/2564 1:01:28 - Microsoft VSIX Installer
5/8/2564 1:01:28 - -------------------------------------------
5/8/2564 1:01:29 - Skipping product Microsoft.VisualStudio.Product.BuildTools (ef603172) since it does not support extensions
5/8/2564 1:01:29 - Initializing Install...
5/8/2564 1:01:30 - Extension Details...
5/8/2564 1:01:30 - 	Identifier         : VSInstallerProjects
5/8/2564 1:01:30 - 	Name               : Microsoft Visual Studio Installer Projects
5/8/2564 1:01:30 - 	Author             : Microsoft
5/8/2564 1:01:30 - 	Version            : 1.0.0
5/8/2564 1:01:30 - 	Description        : This official Microsoft extension provides support for Visual Studio Installer Projects in Visual Studio.
5/8/2564 1:01:30 - 	Locale             : en-US
5/8/2564 1:01:30 - 	MoreInfoURL        : 
5/8/2564 1:01:30 - 	InstalledByMSI     : False
5/8/2564 1:01:30 - 	SupportedFrameworkVersionRange : [4.6.1,)
5/8/2564 1:01:30 - 
5/8/2564 1:01:31 - 	SignatureState     : ValidSignature
5/8/2564 1:01:31 - 	SignedBy           : Microsoft Corporation
5/8/2564 1:01:31 - 	Certificate Info   : 
5/8/2564 1:01:31 - 		-------------------------------------------------------
5/8/2564 1:01:31 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/8/2564 1:01:31 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
5/8/2564 1:01:31 - 		[Serial Number] : 33000003C93EFB7FE21A3D22B30000000003C9
5/8/2564 1:01:31 - 		[Not Before]    : 16/12/2563 4:24:05
5/8/2564 1:01:31 - 		[Not After]     : 3/12/2564 4:24:05
5/8/2564 1:01:31 - 		[Thumbprint]    : E120FF932F2D4DFB59B1DA16BA7C397119E2DEBF
5/8/2564 1:01:31 - 
5/8/2564 1:01:31 - 	Supported Products : 
5/8/2564 1:01:31 - 		Microsoft.VisualStudio.Community
5/8/2564 1:01:31 - 			Version : [15.0,17.0)
5/8/2564 1:01:31 - 
5/8/2564 1:01:31 - 	References         : 
5/8/2564 1:01:31 - 	Prerequisites      : 
5/8/2564 1:01:31 - 		-------------------------------------------------------
5/8/2564 1:01:31 - 		Identifier   : Microsoft.VisualStudio.MinShell
5/8/2564 1:01:31 - 		Name         : Visual Studio Min Shell
5/8/2564 1:01:31 - 		Version      : [15.0.26205,17.0)
5/8/2564 1:01:31 - 
5/8/2564 1:01:31 - 		-------------------------------------------------------
5/8/2564 1:01:31 - 		Identifier   : Microsoft.Component.ClickOnce
5/8/2564 1:01:31 - 		Name         : ClickOnce Publishing
5/8/2564 1:01:31 - 		Version      : [15.0,17.0)
5/8/2564 1:01:31 - 
5/8/2564 1:01:31 - Signature Details...
5/8/2564 1:01:31 - 	Extension is signed with a valid signature.
5/8/2564 1:01:31 - 
5/8/2564 1:01:31 - Searching for applicable products...
5/8/2564 1:01:31 - Found installed product - Global Location
5/8/2564 1:01:31 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
